2025-03-15 12:33:19,750 ERROR: Exception on /translate [POST] [in /Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py:875])]
Traceback (most recent call last):
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/routes.py", line 202, in translate_text
    return {'text': translate.translate(data['text'],
                                        ~~~~^^^^^^^^
KeyError: 'text'
2025-03-15 12:35:16,288 ERROR: Exception on /translate [POST] [in /Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py:875])]
Traceback (most recent call last):
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/routes.py", line 202, in translate_text
    return {'text': translate.translate(data['text'],
                                        ~~~~^^^^^^^^
KeyError: 'text'
2025-03-15 12:35:51,260 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:35:52,032 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:35:59,448 ERROR: Exception on /translate [POST] [in /Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py:875])]
Traceback (most recent call last):
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/routes.py", line 203, in translate_text
    data['source_language'], data['target_language'])}
                             ~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'target_language'
2025-03-15 12:37:49,735 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:37:50,609 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:37:59,462 ERROR: Exception on /translate [POST] [in /Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py:875])]
Traceback (most recent call last):
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/routes.py", line 202, in translate_text
    return {'text': translate.translate(data['text'],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/translate.py", line 51, in translate
    return result.json()['response'][0]['translatedText']
           ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'
2025-03-15 12:38:37,159 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:38:37,936 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:38:56,309 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:39:02,088 ERROR: Exception on /translate [POST] [in /Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py:875])]
Traceback (most recent call last):
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/routes.py", line 202, in translate_text
    return {'text': translate.translate(data['text'],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leosilva/development/microblog/app/translate.py", line 51, in translate
    return result.json()
           ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'
2025-03-15 12:39:21,288 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
2025-03-15 12:39:22,108 INFO: Microblog startup [in /Users/leosilva/development/microblog/app/__init__.py:58])]
